### ISSUE TITLE
Okteto devflow docs appear to be missing some detail needed

### ISSUE THREAD

**Issue by damienomurchu** [litmuschaos/litmus-go#229]
Just trying to validate a [new experiment](https://github.com/damienomurchu/litmus-go/tree/aws-az-down) using the [okteto dev flow steps](https://github.com/litmuschaos/litmus-go/blob/b1f82f5e23cf7275d00aeec3ecdc326c82078821/contribute/developer-guide/README.md#steps-to-test-experiment). UPDATE: changes are now in a draft PR (#230 )

This line looks like it needs to be updated:
```sh
❯ go run experiments/kube-aws/az-down/experiment/az-down.go 
go run: cannot run non-main package
```

Instead I ran the experiment with `bin/go-runner.go`, but it seems I'm missing a step (it wasn't clear how/ if I needed to setup a chaosengine to test the experiment with okteto) - any thoughts?

```
litmus:litmus-experiment okteto> go run bin/go-runner.go -name az-down
W1208 16:01:12.905209    2519 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
INFO[2020-12-08T16:01:12Z] Experiment Name: az-down                     
INFO[2020-12-08T16:01:12Z] [PreReq]: Getting the ENV for the  experiment 
FATAL[2020-12-08T16:01:12Z] Unable to initialise probes details from chaosengine, err: Unable to Get the chaosengine, err: resource name may not be empty 
exit status 1
```

On a sidenote, I've been using an Openshift 4 cluster to validate this and needed to add perms to the experiment serviceaccount to run privileged containers for okteto to be able to create the `litmus-experiment` pod, fyi.

**Comment by ksatchit** [comment]
Hi @damienomurchu - thanks for using the dev guide (we also have some context [here](https://dev.to/ksatchit/litmus-sdk-devtest-your-chaos-experiments-with-okteto-4dkj), if you'd like - a bit stale but the theory holds). 

The idea with Okteto is to provide a dev environment in the cluster. We are launching a dummy/test deployment (test.yaml) with all the actual experiment dependencies built-in (ENVs, configmaps, secrets etc.,) - with the test image being replaced by the okteto dev container upon doing `okteto up` - from which the experiment can be launched via the <go run> commands (followed by code-changes/re-run until expected behavior) 

Once the experiment code displays desired behaviour, you can actually populate the: 

-  chaosexperiment (generated as part of the litmus-sdk command / but can be constructed based on other examples) 
-  chaosengine CRs (needs to be manually constructed, again based on other examples).  
-  construct/use the rbac (you might have this already from the devtest period using okteto) for providing it in the .spec.chaosServiceAccount in the chaosengine. 

Once these artifacts are available you can create the chaosengine to see the creation of chaos-runner and az-experiment pod, followed by chaos injection.

**Comment by damienomurchu** [comment]
Thanks @ksatchit - that's great, will review what you added and linked :+1:

**Comment by ksatchit** [comment]
Thanks. Having said that -- we should ideally not see `FATAL[2020-12-08T16:01:12Z] Unable to initialise probes details from chaosengine, err: Unable to Get the chaosengine, err: resource name may not be empty exit status 1` -- when doing the `go run experiment.go` step. (unless you have a CHAOSENGINE env). cc: @ispeakc0de thoughts?

**Comment by damienomurchu** [comment]
Just to confirm no `CHAOSENGINE` env var set;

```
litmus:litmus-experiment okteto> env | grep CHAOS
CHAOS_NAMESPACE=litmus
TOTAL_CHAOS_DURATION=300
CHAOS_SERVICE_ACCOUNT=scheduler
```

**Comment by ksatchit** [comment]
Suppose needs a fix. Hope to get back on this soon!

**Comment by damienomurchu** [comment]
> Suppose needs a fix. Hope to get back on this soon!

Thanks @ispeakc0de & @ksatchit for the fix! 

I had been working around it by disabling the error checking around the probe and chaosengine, but will rebase against the latest master now its been patched :+1:

**Comment by ksatchit** [comment]
Fixed by https://github.com/litmuschaos/litmus-go/pull/235

Has been added to scaffold: https://github.com/litmuschaos/litmus-go/pull/237
